const CG_CENTER=[-20.4697,-54.6201];
const map=L.map('map',{zoomControl:true}).setView(CG_CENTER,12);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const layer=L.layerGroup().addTo(map),$=id=>document.getElementById(id),cacheKey='radares-cg-geocache-v2';
let geoCache=JSON.parse(localStorage.getItem(cacheKey)||'{}'),userMarker=null,filtered=[];
let all=[...(window.RADARES_PART1||[]),...(window.RADARES_PART2||[])].map(x=>({id:x[0],endereco_original:x[1],velocidade:x[2],tipo:x[3],sentido:x[4],faixas:x[5],lat:null,lng:null}));
function key(r){return r.endereco_original+', Campo Grande, Mato Grosso do Sul, Brasil'}
function applyCache(){for(const r of all){const p=geoCache[key(r)];if(p){r.lat=p.lat;r.lng=p.lng}}}
function markerIcon(speed){return L.divIcon({className:'',html:`<div class="radar-marker ${speed===30?'m30':'m50'}">${speed}</div>`,iconSize:[38,38],iconAnchor:[19,19],popupAnchor:[0,-18]})}
function mapsUrl(r){return r.lat&&r.lng?`https://www.google.com/maps/search/?api=1&query=${r.lat},${r.lng}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(key(r))}`}
function popupHtml(r){return `<div class="popup"><h3>${r.velocidade} km/h</h3><p><strong>${r.endereco_original}</strong></p><p>Tipo: ${r.tipo}</p><p>Sentido: ${r.sentido||'não informado'} · Faixas: ${r.faixas||'-'}</p><p>Código: ${r.id}</p><a href="${mapsUrl(r)}" target="_blank" rel="noopener">Abrir no Google Maps</a></div>`}
function render(){const q=$('search').value.trim().toLowerCase(),sp=$('speedFilter').value,tp=$('typeFilter').value;filtered=all.filter(r=>{const hay=`${r.id} ${r.endereco_original} ${r.tipo} ${r.sentido}`.toLowerCase();return(!q||hay.includes(q))&&(sp==='all'||String(r.velocidade)===sp)&&(tp==='all'||r.tipo===tp)});layer.clearLayers();let mapped=0;for(const r of filtered){if(Number.isFinite(r.lat)&&Number.isFinite(r.lng)){mapped++;L.marker([r.lat,r.lng],{icon:markerIcon(r.velocidade)}).addTo(layer).bindPopup(popupHtml(r))}}$('count').textContent=`${filtered.length} registros · ${mapped} pontos posicionados`;$('list').innerHTML=filtered.length?filtered.map(r=>`<article class="card" data-id="${r.id}"><div class="row"><div class="address">${r.endereco_original}</div><span class="badge ${r.velocidade===30?'speed30':'speed50'}">${r.velocidade} km/h</span></div><div class="type">${r.tipo}</div><div class="meta">${r.id} · sentido ${r.sentido||'-'} · ${r.faixas||'-'} faixa(s) ${r.lat?'· 📍 mapeado':'· ⏳ sem coordenada'}</div></article>`).join(''):'<div class="empty">Nenhum radar encontrado.</div>';document.querySelectorAll('.card').forEach(el=>el.onclick=()=>{const r=all.find(x=>x.id===el.dataset.id);if(r?.lat&&r?.lng){map.setView([r.lat,r.lng],17);L.popup().setLatLng([r.lat,r.lng]).setContent(popupHtml(r)).openOn(map)}})}
async function geocodeOne(q){const resp=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=br&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}});if(!resp.ok)throw Error(`HTTP ${resp.status}`);const d=await resp.json();return d.length?{lat:Number(d[0].lat),lng:Number(d[0].lon)}:null}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function prepareMap(){$('btnGeocode').disabled=true;const unique=[...new Set(all.filter(r=>!(r.lat&&r.lng)).map(key))];for(let i=0;i<unique.length;i++){const q=unique[i];$('geoStatus').textContent=`Geocodificando ${i+1}/${unique.length}...`;try{if(!geoCache[q]){const p=await geocodeOne(q);if(p){geoCache[q]=p;localStorage.setItem(cacheKey,JSON.stringify(geoCache))}}}catch(e){console.warn(e)}applyCache();render();await sleep(1150)}$('geoStatus').textContent=`Concluído. ${Object.keys(geoCache).length} endereços em cache.`;$('btnGeocode').disabled=false;const pts=filtered.filter(r=>r.lat&&r.lng).map(r=>[r.lat,r.lng]);if(pts.length)map.fitBounds(L.latLngBounds(pts).pad(.06))}
function exportJson(){applyCache();const blob=new Blob([JSON.stringify(all,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='radares.geocodificados.json';a.click();URL.revokeObjectURL(a.href)}
$('btnLocate').onclick=()=>{if(!navigator.geolocation)return alert('Geolocalização não disponível.');navigator.geolocation.getCurrentPosition(pos=>{const p=[pos.coords.latitude,pos.coords.longitude];if(userMarker)map.removeLayer(userMarker);userMarker=L.circleMarker(p,{radius:9,weight:3,fillOpacity:.8}).addTo(map).bindPopup('Você está aqui').openPopup();map.setView(p,15)},()=>alert('Não foi possível acessar sua localização.'))};
['search','speedFilter','typeFilter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('btnGeocode').onclick=prepareMap;$('btnExport').onclick=exportJson;applyCache();render();$('geoStatus').textContent=all.some(r=>r.lat&&r.lng)?'Há pontos já posicionados.':'Clique em “Preparar pontos do mapa” para localizar os endereços.';